DROP TABLE BOOKS_OUT_ON_LOAN;
DROP TABLE BOOK;
DROP TABLE USERS;

CREATE TABLE USERS (
    USER_ID           UUID DEFAULT gen_random_uuid(),
    ADDRESS          character varying( 40 ) NOT NULL,
    ADDRESS_ZIP      character varying( 10 ) NOT NULL,
    BIRTHDATE        DATE NOT NULL,
    NAME             character varying( 40 ) NOT NULL,
    PHONE      character varying( 40 ),
    EMAIL       character varying( 40 ),
    CONSTRAINT PK_USERS PRIMARY KEY(USER_ID)) ;

ALTER TABLE USERS ADD CONSTRAINT unique_users UNIQUE (NAME, PHONE);

CREATE TABLE BOOK (
    BOOK_ID           UUID DEFAULT gen_random_uuid(),
    AUTHOR          character varying( 400 ) NOT NULL,
    TITLE            character varying( 4000 ) UNIQUE NOT NULL,
    BOOK_CODE         UUID,
    CONSTRAINT PK_BOOK PRIMARY KEY(BOOK_ID));

ALTER TABLE BOOK ADD CONSTRAINT unique_book UNIQUE (TITLE);

CREATE TABLE BOOKS_OUT_ON_LOAN (
    LOAN_BOOK_ID      UUID DEFAULT gen_random_uuid(),
    BOOK_ID           UUID NOT NULL,
    USER_ID           UUID NOT NULL,
    LOAN_DATE        DATE NOT NULL,
    LOAN_DAYS        integer NOT NULL,
    CONSTRAINT PK_LOAN_BOOK PRIMARY KEY( LOAN_BOOK_ID ),
    CONSTRAINT FK_LOAN_BOOKS FOREIGN KEY( BOOK_ID ) REFERENCES BOOK ( BOOK_ID ) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_LOAN_USERS FOREIGN KEY( USER_ID ) REFERENCES USERS ( USER_ID ) ON DELETE CASCADE ON UPDATE CASCADE) ;

ALTER TABLE BOOKS_OUT_ON_LOAN ADD CONSTRAINT unique_books_loan UNIQUE (BOOK_ID, USER_ID);
--
-- CREATE TABLE PERSON (
--     ID SERIAL NOT NULL PRIMARY KEY,
--     NAME character varying(50)
-- )